C:\Users\Daniel\Desktop\Lab Stuff\SIDEOPENINGBRACKET2V3-Static 1
C:\Users\Daniel\Desktop\Lab Stuff\SIDEOPENINGBRACKET2V3-Static 1
C:\Users\Daniel\Desktop\Lab Stuff\SIDEOPENINGBRACKET2V3-Static 1
C:\Users\Daniel\Desktop\Lab Stuff\SIDEOPENINGBRACKET2V3-Static 1
C:\Users\Daniel\Desktop\Lab Stuff\SIDEOPENINGBRACKET2V3-Static 1
C:\Users\Daniel\Desktop\Lab Stuff\SIDEOPENINGBRACKET2V3-Static 1
C:\Users\Daniel\Desktop\Lab Stuff\SIDEOPENINGBRACKET2V3-Static 1
C:\Users\Daniel\Desktop\Lab Stuff\SIDEOPENINGBRACKET2V3-Static 1
